[package]
name = "shiko-prompt"
version = "0.0.1"
edition = "2024"

[dependencies]
dirs = "4.0"
regex = "1.11.1"
serde = { version = "1.0", features = ["derive"] }
ron = "0.8"
lazy_static = "1.4.0"
string-builder = "0.2.0"
serde_json = "1.0.149"
